### ISSUE TITLE
Symbols not supported in message 

### ISSUE THREAD

**Issue by beeeku** [hirenrojasara/Msg91#4]
When I try to include any symbols like @ # $ % &  the message sends only the part before the symbols . Any fix around that ?

**Comment by beeeku** [comment]
Found the issue here http://help.msg91.com/article/59-problem-with-plus-sign-api-send-sms 
let me know  you can fix it or need a pull request

**Comment by Pankajtanwarbanna** [comment]
I don't think this is an issue. I just sent message with all these symbols. It is working fine.

Still issues? You can go for msg91 another api - https://www.npmjs.com/package/msg91-sms

Thanks

**Comment by beeeku** [comment]
@Pankajtanwarbanna  issue was created in 2016 when there was this issue. I have created a pull request in the official repo to solve this . 
Checkout - [https://github.com/MSG91/MSG91-node/pull/1](https://github.com/MSG91/MSG91-node/pull/1)
